=== vinayprakash893/azure-terrafrom-vny-actions/json/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Additional_App_Infra": {
      "type": "object",
      "properties": {
        "Blob_Storage_Type": {
          "type": "object",
          "properties": {
            "Enabled": {
              "enum": ["True", "true","False","false"]
            },
            "Type": {
              "type": "string"
            }
          },
          "required": [
            "Enabled",
            "Type"
          ]
        },
        "Client_DB_Integration": {
          "type": "object",
          "properties": {
            "Enabled": {
              "enum": ["True", "true","False","false"]
            }
          },
          "required": [
            "Enabled"
          ]
        },
        "DFID_Integration": {
          "type": "object",
          "properties": {
            "Enabled": {
              "enum": ["True", "true","False","false"]
            }
          },
          "required": [
            "Enabled"
          ]
        },
        "Kafka": {
          "type": "object",
          "properties": {
            "Enabled": {
              "type": "string"
            },
            "Type": {
              "type": "string"
            }
          },
          "required": [
            "Enabled",
            "Type"
          ]
        },
        "Redis": {
          "type": "object",
          "properties": {
            "Enabled": {
              "enum": ["True", "true","False","false"]
            },
            "Size": {
              "type": "string"
            }
          },
          "required": [
            "Enabled",
            "Size"
          ]
        },
        "Regional_DB_Integration": {
          "type": "object",
          "properties": {
            "Enabled": {
              "enum": ["True", "true","False","false"]
            }
          },
          "required": [
            "Enabled"
          ]
        }
        
      },
      "required": [
        "Blob_Storage_Type",
        "Kafka",
        "Redis",
        "Client_DB_Integration",
        "Regional_DB_Integration",
        "DFID_Integration"
      ]
    },
    "Application_Name": {
      "type": "string",
      "pattern": "^(?!-)[a-z0-9-]{3,24}$"
    },
    "Application_Short_Name": {
      "type": "string",
        "pattern": "^(?!-)[a-z0-9-]{3,8}$"
    },
    "BillTo": {
      "enum": ["Dayforce Development", "Implementation", "Cloud", "Data"]
    },
    "Cluster_Ref": {
      "type": "string",
			"pattern": "^([a-z]{3})(\\d{2})$"
    },
    "Dayforce_Product_Domain": {
      "enum": ["Data Services", "HR", "Integration", "Intelligent Experience", "Payment Gateway", "Payroll", "People Experience", "People Intelligence", "Platform", "Talent", "Tax", "Wallet", "WFM"]
    },
    "Development": {
      "type": "object",
      "properties": {
        "Manager_Name": {
          "type": "string"
        },
        "Team_Email_Distribution": {
          "type": "string",
					"format": "email"
        },
        "Main_Contact_Name": {
          "type": "string",
            "pattern": "^[a-zA-Z]+ [a-zA-Z]+$"
        },
        "Product_Owner_Email": {
          "type": "string",
					"format": "email"
        },
        "Product_Owner_Name": {
          "type": "string",
            "pattern": "^[a-zA-Z]+ [a-zA-Z]+$"
        },
        "Feature_Team_Name": {
          "type": "string",
            "pattern": "^[a-zA-Z]+ [a-zA-Z]+$"
        }
      },
      "required": [
        "Manager_Name",
        "Team_Email_Distribution",
        "Main_Contact_Name",
        "Product_Owner_Email",
        "Product_Owner_Name",
        "Feature_Team_Name"
      ]
    },
    "Estimated_Go-Live_Date": {
      "type": "string",
			"format": "date"
    },
    "Key": {
      "type": "string",
			"pattern": "^([A-Z-]{2,5}-)(\\d{2})$"
    },
    "Platform": {
      "enum": ["cam", "cie", "cok"]
    },
    "Region": {
      "enum": ["eastus2","centralus","westeurope","northeurope","canadacentral","canadaeast","australiaeast","australiasoutheast"]
    },
    "Service_Tier": {
      "enum": ["Tier 0", "Tier 1", "Tier 2", "Tier 5"]
    },
    "Sub_Environment": {
      "enum": ["dev", "qa", "perf", "stg", "demo", "supp", "conf", "edu", "prod", "np", "pre"]
    },
    "Subscription": {
      "type": "string",
			"pattern": "^([a-z]{3})(\\d{3})$"
    },
    "Version": {
      "type": "object",
      "properties": {
        "Tag": {
          "type": "string",
          "pattern": "^v\\d+\\.\\d+\\.\\d+$"
        }
      },
      "required": [
        "Tag"
      ]
    }
  },
  "required": [
    "Version",
    "Application_Name",
    "Application_Short_Name",
    "Additional_App_Infra",
    "BillTo",
    "Dayforce_Product_Domain",
    "Development",
    "Sub_Environment",
    "Estimated_Go-Live_Date",
    "Key",
    "Platform",
    "Service_Tier",
    "Subscription",
    "Region",
    "Cluster_Ref"
  ]
}

=== vinayprakash893/azure-terrafrom-vny-actions/infra_kit-V1.5/input.json
{
  "Version": {
    "Tag" : "infraeng-json"
  },
  "Application_Name": "dfcoreinfraeng",
  "Application_Short_Name": "infraeng",
  "Additional_App_Infra": {
    "Blob_Storage_Type": {
      "Enabled": "True",
      "Type": "Standard"
    },
    "Kafka": {
      "Enabled": "True",
      "Type": "consumer" 
    },
    "Redis": {
      "Enabled": "True",
      "Size": "small" 
    },
    "Client_DB_Integration": {
      "Enabled": "True"
    },
    "Regional_DB_Integration": {
      "Enabled": "True"
    },
    "DFID_Integration": {
      "Enabled": "True"
    }
  },
  "BillTo": "Dayforce Development",
  "Dayforce_Product_Domain": "WFM",
  "Development": { 
    "Manager_Name": "infraeng Managername",
    "Team_Email_Distribution": "cloudinfrastructureengineering@ceridian.com",
    "Main_Contact_Name": "Infra MainContact",
    "Product_Owner_Email": "infraeng@ceridian.com",
    "Product_Owner_Name": "infraeng owner",
    "Feature_Team_Name" : "featureteam"
  },
  "Sub_Environment": "dev",
  "Estimated_Go-Live_Date": "2024-02-23",
  "Key": "COKSB-53",
  "Platform": "cam",
  "Service_Tier": "Tier 0",
  "Subscription": "app551", 
  "Region": "eastus2",
  "Cluster_Ref": "app98"
}
